# Generated by Django 4.2.7 on 2023-12-02 13:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
